apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wgoat-pd-ing
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: wgoat-pd-svc
          servicePort: 8080
